In [1]:
import pandas as pd
from pandas.core.interchange.dataframe_protocol import DataFrame

df_core = pd.read_csv('ohchr_instruments-core.csv')
df_universal = pd.read_csv('ohchr_instruments-universal.csv')

In [2]:
df_core.tail()

,title,adopted_text,url
13,Optional Protocol to the Convention on the Rig...,ADOPTED 25 MAY 2000,https://www.ohchr.org/en/instruments-mechanism...
14,Optional Protocol to the Convention on the Rig...,ADOPTED 25 MAY 2000,https://www.ohchr.org/en/instruments-mechanism...
15,Optional Protocol to the International Covenan...,ADOPTED 16 DEC 1966,https://www.ohchr.org/en/instruments-mechanism...
16,Optional Protocol to the International Covenan...,ADOPTED 10 DEC 2008,https://www.ohchr.org/en/instruments-mechanism...
17,Second Optional Protocol to the International ...,ADOPTED 15 DEC 1989,https://www.ohchr.org/en/instruments-mechanism...

In [3]:
df_universal.tail()

,page,title,adopted_text,url
89,3,Universal Declaration on Cultural Diversity,ADOPTED 02 NOV 2001,https://www.ohchr.org/en/instruments-mechanism...
90,3,Universal Declaration on the Eradication of Hu...,ADOPTED 16 NOV 1974,https://www.ohchr.org/en/instruments-mechanism...
91,3,Universal Declaration on the Human Genome and ...,ADOPTED 11 NOV 1997,https://www.ohchr.org/en/instruments-mechanism...
92,3,Vienna Declaration and Programme of Action,ADOPTED 25 JUN 1993,https://www.ohchr.org/en/instruments-mechanism...
93,3,"Worst Forms of Child Labour Convention, 1999 (...",ADOPTED 17 JUN 1999,https://www.ohchr.org/en/instruments-mechanism...

In [13]:
print('Number of instruments in core', len(df_core.index))
print('Number of instruments in universal', len(df_universal.index))

print('Core instruments in the universal instruments: ', len(df_universal[df_universal['title'].isin(df_core['title'])]))

print('Universal instruments in the core instruments: ', len(df_core[df_core['title'].isin(df_universal['title'])]))

Number of instruments in core 18
Number of instruments in universal 94
Core instruments in the universal instruments:  12
Universal instruments in the core instruments:  12

In [25]:
df = pd.concat([df_core, df_universal])
df.drop_duplicates(subset='title', keep='last', inplace=True)
df.reset_index(drop=True, inplace=True)

In [26]:
# Drop the 'page' column
if 'page' in df.columns:
    df.drop(columns=['page'], inplace=True)

df.to_csv('./ohchr_instruments.csv', index=False)